# Generated by Django 2.1.3 on 2019-09-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_verify_question', models.CharField(max_length=40)),
                ('user_verify_answer', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'user_verify',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_phone', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('user_password', models.CharField(max_length=35)),
                ('user_nickname', models.CharField(max_length=30)),
                ('user_pic', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='secure',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_verify', to='reg_login.User'),
        ),
    ]
